/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UIndexRouteImport } from './routes/u.index'
import { Route as UCalendarioRouteImport } from './routes/u.calendario'
import { Route as UCostumiRouteImport } from './routes/u.costumi'
import { Route as UMaterialeRouteImport } from './routes/u.materiale'
import { Route as UNotificheRouteImport } from './routes/u.notifiche'
import { Route as UProfiloRouteImport } from './routes/u.profilo'
import { Route as UBollaCodeRouteImport } from './routes/u.bolla.$code'
import { Route as UEventiIndexRouteImport } from './routes/u.eventi.index'
import { Route as UEventiCodeRouteImport } from './routes/u.eventi.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIndexRoute = UIndexRouteImport.update({
  id: '/u/',
  path: '/u/',
  getParentRoute: () => rootRouteImport,
} as any)
const UCalendarioRoute = UCalendarioRouteImport.update({
  id: '/u/calendario',
  path: '/u/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const UCostumiRoute = UCostumiRouteImport.update({
  id: '/u/costumi',
  path: '/u/costumi',
  getParentRoute: () => rootRouteImport,
} as any)
const UMaterialeRoute = UMaterialeRouteImport.update({
  id: '/u/materiale',
  path: '/u/materiale',
  getParentRoute: () => rootRouteImport,
} as any)
const UNotificheRoute = UNotificheRouteImport.update({
  id: '/u/notifiche',
  path: '/u/notifiche',
  getParentRoute: () => rootRouteImport,
} as any)
const UProfiloRoute = UProfiloRouteImport.update({
  id: '/u/profilo',
  path: '/u/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const UBollaCodeRoute = UBollaCodeRouteImport.update({
  id: '/u/bolla/$code',
  path: '/u/bolla/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UEventiIndexRoute = UEventiIndexRouteImport.update({
  id: '/u/eventi/',
  path: '/u/eventi/',
  getParentRoute: () => rootRouteImport,
} as any)
const UEventiCodeRoute = UEventiCodeRouteImport.update({
  id: '/u/eventi/$code',
  path: '/u/eventi/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u/calendario': typeof UCalendarioRoute
  '/u/costumi': typeof UCostumiRoute
  '/u/materiale': typeof UMaterialeRoute
  '/u/notifiche': typeof UNotificheRoute
  '/u/profilo': typeof UProfiloRoute
  '/u/': typeof UIndexRoute
  '/u/bolla/$code': typeof UBollaCodeRoute
  '/u/eventi/$code': typeof UEventiCodeRoute
  '/u/eventi/': typeof UEventiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/u/calendario': typeof UCalendarioRoute
  '/u/costumi': typeof UCostumiRoute
  '/u/materiale': typeof UMaterialeRoute
  '/u/notifiche': typeof UNotificheRoute
  '/u/profilo': typeof UProfiloRoute
  '/u': typeof UIndexRoute
  '/u/bolla/$code': typeof UBollaCodeRoute
  '/u/eventi/$code': typeof UEventiCodeRoute
  '/u/eventi': typeof UEventiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/u/calendario': typeof UCalendarioRoute
  '/u/costumi': typeof UCostumiRoute
  '/u/materiale': typeof UMaterialeRoute
  '/u/notifiche': typeof UNotificheRoute
  '/u/profilo': typeof UProfiloRoute
  '/u/': typeof UIndexRoute
  '/u/bolla/$code': typeof UBollaCodeRoute
  '/u/eventi/$code': typeof UEventiCodeRoute
  '/u/eventi/': typeof UEventiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/u/calendario'
    | '/u/costumi'
    | '/u/materiale'
    | '/u/notifiche'
    | '/u/profilo'
    | '/u/'
    | '/u/bolla/$code'
    | '/u/eventi/$code'
    | '/u/eventi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/u/calendario'
    | '/u/costumi'
    | '/u/materiale'
    | '/u/notifiche'
    | '/u/profilo'
    | '/u'
    | '/u/bolla/$code'
    | '/u/eventi/$code'
    | '/u/eventi'
  id:
    | '__root__'
    | '/'
    | '/u/calendario'
    | '/u/costumi'
    | '/u/materiale'
    | '/u/notifiche'
    | '/u/profilo'
    | '/u/'
    | '/u/bolla/$code'
    | '/u/eventi/$code'
    | '/u/eventi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UCalendarioRoute: typeof UCalendarioRoute
  UCostumiRoute: typeof UCostumiRoute
  UMaterialeRoute: typeof UMaterialeRoute
  UNotificheRoute: typeof UNotificheRoute
  UProfiloRoute: typeof UProfiloRoute
  UIndexRoute: typeof UIndexRoute
  UBollaCodeRoute: typeof UBollaCodeRoute
  UEventiCodeRoute: typeof UEventiCodeRoute
  UEventiIndexRoute: typeof UEventiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/': {
      id: '/u/'
      path: '/u'
      fullPath: '/u/'
      preLoaderRoute: typeof UIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/calendario': {
      id: '/u/calendario'
      path: '/u/calendario'
      fullPath: '/u/calendario'
      preLoaderRoute: typeof UCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/costumi': {
      id: '/u/costumi'
      path: '/u/costumi'
      fullPath: '/u/costumi'
      preLoaderRoute: typeof UCostumiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/materiale': {
      id: '/u/materiale'
      path: '/u/materiale'
      fullPath: '/u/materiale'
      preLoaderRoute: typeof UMaterialeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/notifiche': {
      id: '/u/notifiche'
      path: '/u/notifiche'
      fullPath: '/u/notifiche'
      preLoaderRoute: typeof UNotificheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/profilo': {
      id: '/u/profilo'
      path: '/u/profilo'
      fullPath: '/u/profilo'
      preLoaderRoute: typeof UProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/bolla/$code': {
      id: '/u/bolla/$code'
      path: '/u/bolla/$code'
      fullPath: '/u/bolla/$code'
      preLoaderRoute: typeof UBollaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/eventi/': {
      id: '/u/eventi/'
      path: '/u/eventi'
      fullPath: '/u/eventi/'
      preLoaderRoute: typeof UEventiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/eventi/$code': {
      id: '/u/eventi/$code'
      path: '/u/eventi/$code'
      fullPath: '/u/eventi/$code'
      preLoaderRoute: typeof UEventiCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UCalendarioRoute: UCalendarioRoute,
  UCostumiRoute: UCostumiRoute,
  UMaterialeRoute: UMaterialeRoute,
  UNotificheRoute: UNotificheRoute,
  UProfiloRoute: UProfiloRoute,
  UIndexRoute: UIndexRoute,
  UBollaCodeRoute: UBollaCodeRoute,
  UEventiCodeRoute: UEventiCodeRoute,
  UEventiIndexRoute: UEventiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
