/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UIndexRouteImport } from './routes/u.index'
import { Route as UEventiIndexRouteImport } from './routes/u.eventi.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UIndexRoute = UIndexRouteImport.update({
  id: '/u/',
  path: '/u/',
  getParentRoute: () => rootRouteImport,
} as any)
const UEventiIndexRoute = UEventiIndexRouteImport.update({
  id: '/u/eventi/',
  path: '/u/eventi/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u/': typeof UIndexRoute
  '/u/eventi/': typeof UEventiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/u': typeof UIndexRoute
  '/u/eventi': typeof UEventiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/u/': typeof UIndexRoute
  '/u/eventi/': typeof UEventiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/u/' | '/u/eventi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/u' | '/u/eventi'
  id: '__root__' | '/' | '/u/' | '/u/eventi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UIndexRoute: typeof UIndexRoute
  UEventiIndexRoute: typeof UEventiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/': {
      id: '/u/'
      path: '/u'
      fullPath: '/u/'
      preLoaderRoute: typeof UIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/eventi/': {
      id: '/u/eventi/'
      path: '/u/eventi'
      fullPath: '/u/eventi/'
      preLoaderRoute: typeof UEventiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UIndexRoute: UIndexRoute,
  UEventiIndexRoute: UEventiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
